annotations:
  anybuild.run/config:
    composer_build_script: post-update-cmd
    composer_enable: true
    name: out
    node_build_command: npm run build
    node_install_inputs:
      - package.json
    node_package_manager: npm
    php_framework: laravel
    php_public_dir: public
    phpix: true
  anybuild.run/provider: laravel
  anybuild.run/version: 0.25.0
  wasmer.io/version: 7.2.1
app_id: da_nBBIbtXUBLX3
env:
  PHPIX_PHP_THREADS: "4"
jobs:
  - action:
      execute:
        command: after_deploy
        cli_args:
          - "--force"
          - "--no-interaction"
    name: after_deploy
    trigger: post-deployment
kind: wasmer.io/App.v0
name: joe123
owner: youssefsaad07999-star
package: sha256:64501fb0d335b9415325422bb8a6a00b49ebde9300588b2cd1c83494656544e0
