kind: wasmer.io/App.v0
name: joe123
owner: youssefsaad07999-star
package: .

env:
  PHPIX_PHP_THREADS: "4"

annotations:
  anybuild.run/provider: laravel
  anybuild.run/version: 0.25.0
  wasmer.io/version: 7.2.1
  anybuild.run/config:
    after_deploy: php artisan migrate --force --no-interaction
    composer_build_script: post-update-cmd
    composer_enable: true
    name: out
    node_build_command: npm run build
    node_install_inputs:
      - package.json
    node_package_manager: npm
    php_framework: laravel
    php_public_dir: public
    phpix: true

jobs:
  - name: after_deploy
    trigger: post-deployment
    action:
      execute:
        command: php artisan migrate --force --no-interaction
